-- phpMyAdmin SQL Dump
-- version 4.6.4
-- https://www.phpmyadmin.net/
--
-- Client :  127.0.0.1
-- Généré le :  Ven 06 Octobre 2017 à 14:03
-- Version du serveur :  5.7.14
-- Version de PHP :  5.6.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `testbench`
--

-- --------------------------------------------------------

--
-- Structure de la table `dictionaries`
--

CREATE TABLE `dictionaries` (
  `id` int(11) NOT NULL,
  `symbol_name` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  `pressed_val_freq` varchar(255) NOT NULL,
  `released_val_freq` varchar(255) NOT NULL,
  `pressed_val_tens` varchar(255) NOT NULL,
  `released_val_tens` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `photo_link` varchar(255) NOT NULL,
  `can_id` varchar(255) NOT NULL,
  `family_id` varchar(255) NOT NULL,
  `timer` int(50) NOT NULL,
  `is_final` int(11) NOT NULL,
  `zone` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Contenu de la table `dictionaries`
--

INSERT INTO `dictionaries` (`id`, `symbol_name`, `type`, `value`, `pressed_val_freq`, `released_val_freq`, `pressed_val_tens`, `released_val_tens`, `description`, `photo_link`, `can_id`, `family_id`, `timer`, `is_final`, `zone`) VALUES
(1, 'PG1', 'button', '', '8b', '0b', '8b', '0b', 'Pref', 'tsui1/bt1.jpg', '000002ad', '1', 5, 1, 0),
(2, 'PG2', 'button', '', '88', '08', '88', '08', 'Sub', 'tsui1/bt2.jpg', '000002ad', '1', 5, 1, 0),
(3, 'PG3', 'button', '', '89', '09', '89', '09', 'N/L', 'tsui1/bt3.jpg', '000002ad', '1', 5, 1, 0),
(4, 'PG4', 'button', '', '8a', '0a', '8a', '0a', 'Store', 'tsui1/bt4.jpg', '000002ad', '1', 5, 1, 0),
(5, 'PG5', 'button', '', '8c', '0c', '8c', '0c', 'X ray timer', 'tsui1/bt5.png', '000002ad', '1', 6, 1, 0),
(6, 'PB1', 'button', '', '8e', '0e', '8e', '0e', 'FOV-', 'tsui1/fov1.png', '000002ad', '1', 5, 1, 1),
(7, 'PB2', 'button', '', '8d', '0d', '8d', '0d', 'FOV+', 'tsui1/fov2.png', '000002ad', '1', 5, 1, 1),
(8, 'PB3', 'button', '', '90', '10', '90', '10', 'Landscape-', 'tsui1/landscape1.png', '000002ad', '1', 5, 1, 1),
(9, 'PB4', 'button', '', '8f', '0f', '8f', '0f', 'Landscape+', 'tsui1/landscape2.png', '000002ad', '1', 5, 1, 1),
(10, 'PB5', 'button', '', '91', '11', '91', '11', 'Room light', 'tsui1/room.png', '000002ad', '1', 5, 1, 1),
(11, 'PB6', 'button', '', 'b3', '33', 'b3', '33', 'Spare Left', 'tsui1/spare1.png', '000002ad', '1', 8, 1, 1),
(12, 'PB7', 'button', '', 'b4', '34', 'b4', '34', 'Spare Middle', 'tsui1/spare2.png', '000002ad', '1', 7, 1, 1),
(13, 'PB8', 'button', '', 'b2', '32', 'b2', '32', 'Spare Right', 'tsui1/spare3.png', '000002ad', '1', 5, 1, 1),
(14, 'PB9', 'button', '', 'a1', '21', 'a1', '21', 'Operator-', 'tsui1/operator1.jpg', '000002ad', '1', 5, 1, 1),
(15, 'PB10', 'button', '', 'a2', '22', 'a2', '22', 'Operator+', 'tsui1/operator2.jpg', '000002ad', '1', 6, 1, 1),
(16, 'PD1', 'button', '', '97', '17', '97', '17', 'Stop', 'tsui1/stop.jpg', '000002ad', '1', 5, 1, 2),
(17, 'PD2', 'button', '', '94', '14', '94', '14', 'S/E', 'tsui1/se.jpg', '000002ad', '1', 5, 1, 2),
(18, 'PD3', 'button', '', '93', '13', '93', '13', 'Test', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 2),
(21, 'emcio hb', 'filter1', '05', '', '', '', '', 'Heartbeat EMCIO', '', '0000072d', '1', 60000, 0, 8),
(22, 'joystick', 'filter2', '000000000000', '', '', '', '', 'joystick', '', '000001ad', '1', 60000, 0, 8),
(23, '', 'joystick', '', '', '', '', '', '', '', '000001ad', '1', 5, 0, 8),
(24, 'LED', 'led', '', 'FFFF000000000000', '0000000000000000', 'FFFF000000000000', '0000000000000000', 'Led Blinking 1', '', '00000228', '1', 5, 0, 8),
(25, 'LED', 'led', '', 'FFFFFFFFFFFFFFFF', '0000000000000000', 'FFFFFFFFFFFFFFFF', '0000000000000000', 'Led Blinking 2', '', '00000328', '1', 5, 0, 8),
(26, 'BUZZER', 'buzzer', '', '01900d2500000000', '', '01900d2500000000', '', 'short bip high volume', '', '00000528', '1', 5, 0, 8),
(27, 'I1', 'joystick', '', '', '', '', '', 'Table Padding Mushroom', '', '000002a5', '3', 5, 0, 8),
(28, 'I2', 'joystick', '', '', '', '', '', 'Pivot & C arm', '', '000002a5', '3', 5, 0, 0),
(29, 'I3', 'joystick', '', '', '', '', '', 'Table motion', '', '000002a5', '3', 5, 0, 0),
(30, 'I4', 'joystick', '', '', '', '', '', 'Detectors Lift', '', '000002a5', '3', 5, 0, 0),
(31, 'I5', 'button', '', '81', '01', '81', '01', 'Machine', '', '000002a5', '3', 5, 1, 0),
(32, 'I6', 'joystick', '', '', '', '', '', 'L arm & lateral carriage', '', '000002a5', '3', 5, 0, 0),
(33, 'I7', 'button', '', '82', '02', '82', '02', 'Lock/Unlock', '', '000002a5', '3', 5, 1, 0),
(34, 'I8', 'button', '', '83', '03', '83', '03', 'Patient Contouring', '', '000002a5', '3', 5, 1, 0),
(35, 'I9', 'button', '', '', '', '', '', 'Sliding Inverter', '', '000002a5', '3', 5, 1, 0),
(36, 'I10', 'button', '', '84', '04', '84', '04', 'Emergency', '', '000002a5', '3', 5, 1, 0),
(37, 'I1', 'button', '', 'b0', '30', 'b0', '30', 'Table padding enable', '', '000002a5', '3', 5, 1, 0),
(38, 'I2', 'button', '', 'b2', '32', 'b2', '32', 'Gantry joystick enable', '', '000002a5', '3', 5, 1, 0),
(39, 'I3', 'button', '', 'b1', '31', 'b1', '31', 'Table driving enable', '', '000002a5', '3', 5, 1, 0),
(40, 'I4', 'button', '', 'b3', '33', 'b3', '33', 'Gantry lift detectors enable', '', '000002a5', '3', 5, 1, 0),
(41, 'I6', 'button', '', 'b4', '34', 'b4', '34', 'Gantry L arm enable', '', '000002a5', '3', 5, 1, 0),
(42, 'SG4', 'button', '', '85', '05', '85', '05', 'CB sat left', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 3),
(43, 'SG2', 'button', '', '86', '06', '86', '06', 'CB sat right', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 3),
(44, 'SG3', 'button', '', '87', '07', '87', '07', 'CB sat down', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 3),
(45, 'SC1', 'button', '', '83', '03', '83', '03', 'CF sat up', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 4),
(46, 'SC4', 'button', '', '81', '01', '81', '01', 'CF sat left', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 4),
(47, 'SC2', 'button', '', '82', '02', '82', '02', 'CF sat right', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 4),
(48, 'SC3', 'button', '', '84', '04', '84', '04', 'CF sat down', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 4),
(49, 'SD7', 'button', '', 'a4', '24', 'A4', '24', 'Autopos 1', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 5),
(50, 'SD8', 'button', '', 'a5', '25', 'a5', '25', 'Autopos 2', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 5),
(51, 'SD1', 'button', '', 'a6', '26', 'a6', '26', 'Autopos 3', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 5),
(52, 'SD2', 'button', '', 'a7', '27', 'a7', '27', 'Autopos 4', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 5),
(53, 'SD3', 'button', '', 'a8', '28', 'a8', '28', 'Autopos 5', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 5),
(54, 'SD6', 'button', '', 'a3', '23', 'a3', '23', 'Store gantry', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 5),
(55, 'SD4', 'button', '', 'a9', '29', 'a9', '29', 'Store table', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 5),
(56, 'SD5', 'button', '', 'ac', '2c', '93', '2c', 'Store both', 'tsui1/test.jpg', '000002ad', '1', 5, 1, 5);

-- --------------------------------------------------------

--
-- Structure de la table `global_log`
--

CREATE TABLE `global_log` (
  `id` int(11) NOT NULL,
  `part_number` varchar(255) NOT NULL,
  `serial_number` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `date` datetime NOT NULL,
  `json_log` json NOT NULL,
  `user_sso` varchar(255) NOT NULL,
  `role` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Contenu de la table `global_log`
--

INSERT INTO `global_log` (`id`, `part_number`, `serial_number`, `type`, `date`, `json_log`, `user_sso`, `role`) VALUES
(1, '', '', 'pretest', '2017-04-19 11:34:43', '[{"name": "PG1 - press", "test": "untested"}, {"name": "PG1 - release", "test": "untested"}, {"name": "PG2 - press", "test": "untested"}, {"name": "PG2 - release", "test": "untested"}, {"name": "PG3 - press", "test": "untested"}, {"name": "PG3 - release", "test": "untested"}, {"name": "PG4 - press", "test": "untested"}, {"name": "PG4 - release", "test": "untested"}, {"name": "PG5 - press", "test": "untested"}, {"name": "PG5 - release", "test": "untested"}, {"name": "PB1 - press", "test": "untested"}, {"name": "PB1 - release", "test": "untested"}, {"name": "PB2 - press", "test": "untested"}, {"name": "PB2 - release", "test": "untested"}, {"name": "PB3 - press", "test": "untested"}, {"name": "PB3 - release", "test": "untested"}, {"name": "PB4 - press", "test": "untested"}, {"name": "PB4 - release", "test": "untested"}, {"name": "PB5 - press", "test": "untested"}, {"name": "PB5 - release", "test": "untested"}, {"name": "PB6 - press", "test": "untested"}, {"name": "PB6 - release", "test": "untested"}, {"name": "PB7 - press", "test": "untested"}, {"name": "PB7 - release", "test": "untested"}, {"name": "PB8 - press", "test": "untested"}, {"name": "PB8 - release", "test": "untested"}, {"name": "PB9 - press", "test": "untested"}, {"name": "PB9 - release", "test": "untested"}, {"name": "PB10 - press", "test": "untested"}, {"name": "PB10 - release", "test": "untested"}, {"name": "PD1 - press", "test": "untested"}, {"name": "PD1 - release", "test": "untested"}, {"name": "PD2 - press", "test": "untested"}, {"name": "PD2 - release", "test": "untested"}, {"name": "PD3 - press", "test": "untested"}, {"name": "PD3 - release", "test": "untested"}, {"name": " - joystick", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(2, '', '', 'pretest', '2017-04-19 11:40:16', '[{"name": "PG1 - press", "test": "untested"}, {"name": "PG1 - release", "test": "untested"}, {"name": "PG2 - press", "test": "untested"}, {"name": "PG2 - release", "test": "untested"}, {"name": "PG3 - press", "test": "untested"}, {"name": "PG3 - release", "test": "untested"}, {"name": "PG4 - press", "test": "untested"}, {"name": "PG4 - release", "test": "untested"}, {"name": "PG5 - press", "test": "untested"}, {"name": "PG5 - release", "test": "untested"}, {"name": "PB1 - press", "test": "untested"}, {"name": "PB1 - release", "test": "untested"}, {"name": "PB2 - press", "test": "untested"}, {"name": "PB2 - release", "test": "untested"}, {"name": "PB3 - press", "test": "untested"}, {"name": "PB3 - release", "test": "untested"}, {"name": "PB4 - press", "test": "untested"}, {"name": "PB4 - release", "test": "untested"}, {"name": "PB5 - press", "test": "untested"}, {"name": "PB5 - release", "test": "untested"}, {"name": "PB6 - press", "test": "untested"}, {"name": "PB6 - release", "test": "untested"}, {"name": "PB7 - press", "test": "untested"}, {"name": "PB7 - release", "test": "untested"}, {"name": "PB8 - press", "test": "untested"}, {"name": "PB8 - release", "test": "untested"}, {"name": "PB9 - press", "test": "untested"}, {"name": "PB9 - release", "test": "untested"}, {"name": "PB10 - press", "test": "untested"}, {"name": "PB10 - release", "test": "untested"}, {"name": "PD1 - press", "test": "untested"}, {"name": "PD1 - release", "test": "untested"}, {"name": "PD2 - press", "test": "untested"}, {"name": "PD2 - release", "test": "untested"}, {"name": "PD3 - press", "test": "untested"}, {"name": "PD3 - release", "test": "untested"}, {"name": " - joystick", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(3, 'testPN', 'testSerial', 'pretest', '2017-04-19 11:53:38', '[{"name": "PG1 - press", "test": "untested"}, {"name": "PG1 - release", "test": "untested"}, {"name": "PG2 - press", "test": "untested"}, {"name": "PG2 - release", "test": "untested"}, {"name": "PG3 - press", "test": "untested"}, {"name": "PG3 - release", "test": "untested"}, {"name": "PG4 - press", "test": "untested"}, {"name": "PG4 - release", "test": "untested"}, {"name": "PG5 - press", "test": "untested"}, {"name": "PG5 - release", "test": "untested"}, {"name": "PB1 - press", "test": "untested"}, {"name": "PB1 - release", "test": "untested"}, {"name": "PB2 - press", "test": "untested"}, {"name": "PB2 - release", "test": "untested"}, {"name": "PB3 - press", "test": "untested"}, {"name": "PB3 - release", "test": "untested"}, {"name": "PB4 - press", "test": "untested"}, {"name": "PB4 - release", "test": "untested"}, {"name": "PB5 - press", "test": "untested"}, {"name": "PB5 - release", "test": "untested"}, {"name": "PB6 - press", "test": "untested"}, {"name": "PB6 - release", "test": "untested"}, {"name": "PB7 - press", "test": "untested"}, {"name": "PB7 - release", "test": "untested"}, {"name": "PB8 - press", "test": "untested"}, {"name": "PB8 - release", "test": "untested"}, {"name": "PB9 - press", "test": "untested"}, {"name": "PB9 - release", "test": "untested"}, {"name": "PB10 - press", "test": "untested"}, {"name": "PB10 - release", "test": "untested"}, {"name": "PD1 - press", "test": "untested"}, {"name": "PD1 - release", "test": "untested"}, {"name": "PD2 - press", "test": "untested"}, {"name": "PD2 - release", "test": "untested"}, {"name": "PD3 - press", "test": "untested"}, {"name": "PD3 - release", "test": "untested"}, {"name": " - joystick", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(4, 'testPN', 'testSerial', 'pretest', '2017-04-19 14:13:57', '[{"name": "PG1 - press", "test": "untested"}, {"name": "PG1 - release", "test": "untested"}, {"name": "PG2 - press", "test": "untested"}, {"name": "PG2 - release", "test": "untested"}, {"name": "PG3 - press", "test": "untested"}, {"name": "PG3 - release", "test": "untested"}, {"name": "PG4 - press", "test": "untested"}, {"name": "PG4 - release", "test": "untested"}, {"name": "PG5 - press", "test": "untested"}, {"name": "PG5 - release", "test": "untested"}, {"name": "PB1 - press", "test": "untested"}, {"name": "PB1 - release", "test": "untested"}, {"name": "PB2 - press", "test": "untested"}, {"name": "PB2 - release", "test": "untested"}, {"name": "PB3 - press", "test": "untested"}, {"name": "PB3 - release", "test": "untested"}, {"name": "PB4 - press", "test": "untested"}, {"name": "PB4 - release", "test": "untested"}, {"name": "PB5 - press", "test": "untested"}, {"name": "PB5 - release", "test": "untested"}, {"name": "PB6 - press", "test": "untested"}, {"name": "PB6 - release", "test": "untested"}, {"name": "PB7 - press", "test": "untested"}, {"name": "PB7 - release", "test": "untested"}, {"name": "PB8 - press", "test": "untested"}, {"name": "PB8 - release", "test": "untested"}, {"name": "PB9 - press", "test": "untested"}, {"name": "PB9 - release", "test": "untested"}, {"name": "PB10 - press", "test": "untested"}, {"name": "PB10 - release", "test": "untested"}, {"name": "PD1 - press", "test": "untested"}, {"name": "PD1 - release", "test": "untested"}, {"name": "PD2 - press", "test": "untested"}, {"name": "PD2 - release", "test": "untested"}, {"name": "PD3 - press", "test": "untested"}, {"name": "PD3 - release", "test": "untested"}, {"name": " - joystick", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(5, 'testPN', 'testSerial', 'pretest', '2017-04-19 14:16:03', '[{"name": "PG1 - press", "test": "untested"}, {"name": "PG1 - release", "test": "untested"}, {"name": "PG2 - press", "test": "untested"}, {"name": "PG2 - release", "test": "untested"}, {"name": "PG3 - press", "test": "untested"}, {"name": "PG3 - release", "test": "untested"}, {"name": "PG4 - press", "test": "untested"}, {"name": "PG4 - release", "test": "untested"}, {"name": "PG5 - press", "test": "untested"}, {"name": "PG5 - release", "test": "untested"}, {"name": "PB1 - press", "test": "untested"}, {"name": "PB1 - release", "test": "untested"}, {"name": "PB2 - press", "test": "untested"}, {"name": "PB2 - release", "test": "untested"}, {"name": "PB3 - press", "test": "untested"}, {"name": "PB3 - release", "test": "untested"}, {"name": "PB4 - press", "test": "untested"}, {"name": "PB4 - release", "test": "untested"}, {"name": "PB5 - press", "test": "untested"}, {"name": "PB5 - release", "test": "untested"}, {"name": "PB6 - press", "test": "untested"}, {"name": "PB6 - release", "test": "untested"}, {"name": "PB7 - press", "test": "untested"}, {"name": "PB7 - release", "test": "untested"}, {"name": "PB8 - press", "test": "untested"}, {"name": "PB8 - release", "test": "untested"}, {"name": "PB9 - press", "test": "untested"}, {"name": "PB9 - release", "test": "untested"}, {"name": "PB10 - press", "test": "untested"}, {"name": "PB10 - release", "test": "untested"}, {"name": "PD1 - press", "test": "untested"}, {"name": "PD1 - release", "test": "untested"}, {"name": "PD2 - press", "test": "untested"}, {"name": "PD2 - release", "test": "untested"}, {"name": "PD3 - press", "test": "untested"}, {"name": "PD3 - release", "test": "untested"}, {"name": " - joystick", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(6, 'testPN', 'testSerial', 'pretest', '2017-04-19 14:17:43', '[{"name": "PG1 - press", "test": "untested"}, {"name": "PG1 - release", "test": "untested"}, {"name": "PG2 - press", "test": "untested"}, {"name": "PG2 - release", "test": "untested"}, {"name": "PG3 - press", "test": "untested"}, {"name": "PG3 - release", "test": "untested"}, {"name": "PG4 - press", "test": "untested"}, {"name": "PG4 - release", "test": "untested"}, {"name": "PG5 - press", "test": "untested"}, {"name": "PG5 - release", "test": "untested"}, {"name": "PB1 - press", "test": "untested"}, {"name": "PB1 - release", "test": "untested"}, {"name": "PB2 - press", "test": "untested"}, {"name": "PB2 - release", "test": "untested"}, {"name": "PB3 - press", "test": "untested"}, {"name": "PB3 - release", "test": "untested"}, {"name": "PB4 - press", "test": "untested"}, {"name": "PB4 - release", "test": "untested"}, {"name": "PB5 - press", "test": "untested"}, {"name": "PB5 - release", "test": "untested"}, {"name": "PB6 - press", "test": "untested"}, {"name": "PB6 - release", "test": "untested"}, {"name": "PB7 - press", "test": "untested"}, {"name": "PB7 - release", "test": "untested"}, {"name": "PB8 - press", "test": "untested"}, {"name": "PB8 - release", "test": "untested"}, {"name": "PB9 - press", "test": "untested"}, {"name": "PB9 - release", "test": "untested"}, {"name": "PB10 - press", "test": "untested"}, {"name": "PB10 - release", "test": "untested"}, {"name": "PD1 - press", "test": "untested"}, {"name": "PD1 - release", "test": "untested"}, {"name": "PD2 - press", "test": "untested"}, {"name": "PD2 - release", "test": "untested"}, {"name": "PD3 - press", "test": "untested"}, {"name": "PD3 - release", "test": "untested"}, {"name": " - joystick", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(7, 'testPN', 'testSerial', 'pretest', '2017-04-19 14:19:47', '[{"name": "PG1 - press", "test": "untested"}, {"name": "PG1 - release", "test": "untested"}, {"name": "PG2 - press", "test": "untested"}, {"name": "PG2 - release", "test": "untested"}, {"name": "PG3 - press", "test": "untested"}, {"name": "PG3 - release", "test": "untested"}, {"name": "PG4 - press", "test": "untested"}, {"name": "PG4 - release", "test": "untested"}, {"name": "PG5 - press", "test": "untested"}, {"name": "PG5 - release", "test": "untested"}, {"name": "PB1 - press", "test": "untested"}, {"name": "PB1 - release", "test": "untested"}, {"name": "PB2 - press", "test": "untested"}, {"name": "PB2 - release", "test": "untested"}, {"name": "PB3 - press", "test": "untested"}, {"name": "PB3 - release", "test": "untested"}, {"name": "PB4 - press", "test": "untested"}, {"name": "PB4 - release", "test": "untested"}, {"name": "PB5 - press", "test": "untested"}, {"name": "PB5 - release", "test": "untested"}, {"name": "PB6 - press", "test": "untested"}, {"name": "PB6 - release", "test": "untested"}, {"name": "PB7 - press", "test": "untested"}, {"name": "PB7 - release", "test": "untested"}, {"name": "PB8 - press", "test": "untested"}, {"name": "PB8 - release", "test": "untested"}, {"name": "PB9 - press", "test": "untested"}, {"name": "PB9 - release", "test": "untested"}, {"name": "PB10 - press", "test": "untested"}, {"name": "PB10 - release", "test": "untested"}, {"name": "PD1 - press", "test": "untested"}, {"name": "PD1 - release", "test": "untested"}, {"name": "PD2 - press", "test": "untested"}, {"name": "PD2 - release", "test": "untested"}, {"name": "PD3 - press", "test": "untested"}, {"name": "PD3 - release", "test": "untested"}, {"name": " - joystick", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(8, 'testPN', 'testSerial', 'pretest', '2017-04-19 14:24:20', '[{"name": "PG1 - press", "test": "untested"}, {"name": "PG1 - release", "test": "untested"}, {"name": "PG2 - press", "test": "untested"}, {"name": "PG2 - release", "test": "untested"}, {"name": "PG3 - press", "test": "untested"}, {"name": "PG3 - release", "test": "untested"}, {"name": "PG4 - press", "test": "untested"}, {"name": "PG4 - release", "test": "untested"}, {"name": "PG5 - press", "test": "untested"}, {"name": "PG5 - release", "test": "untested"}, {"name": "PB1 - press", "test": "untested"}, {"name": "PB1 - release", "test": "untested"}, {"name": "PB2 - press", "test": "untested"}, {"name": "PB2 - release", "test": "untested"}, {"name": "PB3 - press", "test": "untested"}, {"name": "PB3 - release", "test": "untested"}, {"name": "PB4 - press", "test": "untested"}, {"name": "PB4 - release", "test": "untested"}, {"name": "PB5 - press", "test": "untested"}, {"name": "PB5 - release", "test": "untested"}, {"name": "PB6 - press", "test": "untested"}, {"name": "PB6 - release", "test": "untested"}, {"name": "PB7 - press", "test": "untested"}, {"name": "PB7 - release", "test": "untested"}, {"name": "PB8 - press", "test": "untested"}, {"name": "PB8 - release", "test": "untested"}, {"name": "PB9 - press", "test": "untested"}, {"name": "PB9 - release", "test": "untested"}, {"name": "PB10 - press", "test": "untested"}, {"name": "PB10 - release", "test": "untested"}, {"name": "PD1 - press", "test": "untested"}, {"name": "PD1 - release", "test": "untested"}, {"name": "PD2 - press", "test": "untested"}, {"name": "PD2 - release", "test": "untested"}, {"name": "PD3 - press", "test": "untested"}, {"name": "PD3 - release", "test": "untested"}, {"name": " - joystick", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(9, 'testPN', 'testSerial', 'pretest', '2017-04-19 15:21:12', '[{"name": "PG1 - press", "test": "untested"}, {"name": "PG1 - release", "test": "untested"}, {"name": "PG2 - press", "test": "untested"}, {"name": "PG2 - release", "test": "untested"}, {"name": "PG3 - press", "test": "untested"}, {"name": "PG3 - release", "test": "untested"}, {"name": "PG4 - press", "test": "untested"}, {"name": "PG4 - release", "test": "untested"}, {"name": "PG5 - press", "test": "untested"}, {"name": "PG5 - release", "test": "untested"}, {"name": "PB1 - press", "test": "untested"}, {"name": "PB1 - release", "test": "untested"}, {"name": "PB2 - press", "test": "untested"}, {"name": "PB2 - release", "test": "untested"}, {"name": "PB3 - press", "test": "untested"}, {"name": "PB3 - release", "test": "untested"}, {"name": "PB4 - press", "test": "untested"}, {"name": "PB4 - release", "test": "untested"}, {"name": "PB5 - press", "test": "untested"}, {"name": "PB5 - release", "test": "untested"}, {"name": "PB6 - press", "test": "untested"}, {"name": "PB6 - release", "test": "untested"}, {"name": "PB7 - press", "test": "untested"}, {"name": "PB7 - release", "test": "untested"}, {"name": "PB8 - press", "test": "untested"}, {"name": "PB8 - release", "test": "untested"}, {"name": "PB9 - press", "test": "untested"}, {"name": "PB9 - release", "test": "untested"}, {"name": "PB10 - press", "test": "untested"}, {"name": "PB10 - release", "test": "untested"}, {"name": "PD1 - press", "test": "untested"}, {"name": "PD1 - release", "test": "untested"}, {"name": "PD2 - press", "test": "untested"}, {"name": "PD2 - release", "test": "untested"}, {"name": "PD3 - press", "test": "untested"}, {"name": "PD3 - release", "test": "untested"}, {"name": " - joystick", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "LED - led", "test": "untested"}, {"name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(10, 'testPN', 'testSerial', 'pretest', '2017-04-19 15:25:00', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(11, 'testPN', 'testSerial', 'pretest', '2017-04-19 15:25:25', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(12, 'testPN', 'testSerial', 'pretest', '2017-04-19 15:36:20', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(13, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:10:36', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(14, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:13:51', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(15, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:14:03', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(16, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:19:16', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(17, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:21:11', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(18, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:22:22', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(19, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:26:49', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(20, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:28:32', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(21, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:29:09', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair');
INSERT INTO `global_log` (`id`, `part_number`, `serial_number`, `type`, `date`, `json_log`, `user_sso`, `role`) VALUES
(22, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:33:30', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(23, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:36:00', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(24, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:37:14', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(25, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:39:13', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(26, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:42:12', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(27, 'testPN', 'testSerial', 'pretest', '2017-04-19 16:43:24', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(28, 'testPN', 'testSerial', 'pretest', '2017-05-10 09:25:52', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "FAILED"}, {"fct": "button", "name": "PG2 - release", "test": "FAILED"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "FAILED"}, {"fct": "button", "name": "PD3 - release", "test": "FAILED"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(29, 'testPN', 'testSerial', 'pretest', '2017-08-03 11:23:50', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(30, 'testPN', 'testSerial', 'pretest', '2017-08-03 12:05:42', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(31, 'testPN', 'testSerial', 'pretest', '2017-08-08 10:13:08', '[{"fct": "button", "name": "PG1 - press", "test": "OK"}, {"fct": "button", "name": "PG1 - release", "test": "OK"}, {"fct": "button", "name": "PG2 - press", "test": "OK"}, {"fct": "button", "name": "PG2 - release", "test": "OK"}, {"fct": "button", "name": "PG3 - press", "test": "OK"}, {"fct": "button", "name": "PG3 - release", "test": "OK"}, {"fct": "button", "name": "PG4 - press", "test": "OK"}, {"fct": "button", "name": "PG4 - release", "test": "OK"}, {"fct": "button", "name": "PG5 - press", "test": "OK"}, {"fct": "button", "name": "PG5 - release", "test": "OK"}, {"fct": "button", "name": "PB1 - press", "test": "OK"}, {"fct": "button", "name": "PB1 - release", "test": "OK"}, {"fct": "button", "name": "PB2 - press", "test": "OK"}, {"fct": "button", "name": "PB2 - release", "test": "OK"}, {"fct": "button", "name": "PB3 - press", "test": "OK"}, {"fct": "button", "name": "PB3 - release", "test": "OK"}, {"fct": "button", "name": "PB4 - press", "test": "OK"}, {"fct": "button", "name": "PB4 - release", "test": "OK"}, {"fct": "button", "name": "PB5 - press", "test": "OK"}, {"fct": "button", "name": "PB5 - release", "test": "OK"}, {"fct": "button", "name": "PB6 - press", "test": "OK"}, {"fct": "button", "name": "PB6 - release", "test": "OK"}, {"fct": "button", "name": "PB7 - press", "test": "OK"}, {"fct": "button", "name": "PB7 - release", "test": "OK"}, {"fct": "button", "name": "PB8 - press", "test": "OK"}, {"fct": "button", "name": "PB8 - release", "test": "OK"}, {"fct": "button", "name": "PB9 - press", "test": "OK"}, {"fct": "button", "name": "PB9 - release", "test": "OK"}, {"fct": "button", "name": "PB10 - press", "test": "OK"}, {"fct": "button", "name": "PB10 - release", "test": "OK"}, {"fct": "button", "name": "PD1 - press", "test": "OK"}, {"fct": "button", "name": "PD1 - release", "test": "OK"}, {"fct": "button", "name": "PD2 - press", "test": "OK"}, {"fct": "button", "name": "PD2 - release", "test": "OK"}, {"fct": "button", "name": "PD3 - press", "test": "OK"}, {"fct": "button", "name": "PD3 - release", "test": "OK"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "FAILED"}]', 'testuser', 'repair'),
(32, 'testPN', 'testSerial', 'pretest', '2017-09-01 12:00:04', '[{"fct": "button", "name": "PG1 - press", "test": "OK"}, {"fct": "button", "name": "PG1 - release", "test": "OK"}, {"fct": "button", "name": "PG2 - press", "test": "OK"}, {"fct": "button", "name": "PG2 - release", "test": "OK"}, {"fct": "button", "name": "PG3 - press", "test": "OK"}, {"fct": "button", "name": "PG3 - release", "test": "OK"}, {"fct": "button", "name": "PG4 - press", "test": "OK"}, {"fct": "button", "name": "PG4 - release", "test": "OK"}, {"fct": "button", "name": "PG5 - press", "test": "OK"}, {"fct": "button", "name": "PG5 - release", "test": "OK"}, {"fct": "button", "name": "PB1 - press", "test": "FAILED"}, {"fct": "button", "name": "PB1 - release", "test": "FAILED"}, {"fct": "button", "name": "PB2 - press", "test": "FAILED"}, {"fct": "button", "name": "PB2 - release", "test": "FAILED"}, {"fct": "button", "name": "PB3 - press", "test": "FAILED"}, {"fct": "button", "name": "PB3 - release", "test": "FAILED"}, {"fct": "button", "name": "PB4 - press", "test": "FAILED"}, {"fct": "button", "name": "PB4 - release", "test": "FAILED"}, {"fct": "button", "name": "PB5 - press", "test": "FAILED"}, {"fct": "button", "name": "PB5 - release", "test": "FAILED"}, {"fct": "button", "name": "PB6 - press", "test": "OK"}, {"fct": "button", "name": "PB6 - release", "test": "OK"}, {"fct": "button", "name": "PB7 - press", "test": "OK"}, {"fct": "button", "name": "PB7 - release", "test": "OK"}, {"fct": "button", "name": "PB8 - press", "test": "OK"}, {"fct": "button", "name": "PB8 - release", "test": "OK"}, {"fct": "button", "name": "PB9 - press", "test": "OK"}, {"fct": "button", "name": "PB9 - release", "test": "OK"}, {"fct": "button", "name": "PB10 - press", "test": "OK"}, {"fct": "button", "name": "PB10 - release", "test": "OK"}, {"fct": "button", "name": "PD1 - press", "test": "OK"}, {"fct": "button", "name": "PD1 - release", "test": "OK"}, {"fct": "button", "name": "PD2 - press", "test": "OK"}, {"fct": "button", "name": "PD2 - release", "test": "OK"}, {"fct": "button", "name": "PD3 - press", "test": "OK"}, {"fct": "button", "name": "PD3 - release", "test": "OK"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "OK"}, {"fct": "led", "name": "LED - led", "test": "OK"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "OK"}]', 'testuser', 'repair'),
(33, 'testPN', 'testSerial', 'pretest', '2017-09-11 13:25:39', '[{"fct": "button", "name": "PG1 - press", "test": "untested"}, {"fct": "button", "name": "PG1 - release", "test": "untested"}, {"fct": "button", "name": "PG2 - press", "test": "untested"}, {"fct": "button", "name": "PG2 - release", "test": "untested"}, {"fct": "button", "name": "PG3 - press", "test": "untested"}, {"fct": "button", "name": "PG3 - release", "test": "untested"}, {"fct": "button", "name": "PG4 - press", "test": "untested"}, {"fct": "button", "name": "PG4 - release", "test": "untested"}, {"fct": "button", "name": "PG5 - press", "test": "untested"}, {"fct": "button", "name": "PG5 - release", "test": "untested"}, {"fct": "button", "name": "PB1 - press", "test": "untested"}, {"fct": "button", "name": "PB1 - release", "test": "untested"}, {"fct": "button", "name": "PB2 - press", "test": "untested"}, {"fct": "button", "name": "PB2 - release", "test": "untested"}, {"fct": "button", "name": "PB3 - press", "test": "untested"}, {"fct": "button", "name": "PB3 - release", "test": "untested"}, {"fct": "button", "name": "PB4 - press", "test": "untested"}, {"fct": "button", "name": "PB4 - release", "test": "untested"}, {"fct": "button", "name": "PB5 - press", "test": "untested"}, {"fct": "button", "name": "PB5 - release", "test": "untested"}, {"fct": "button", "name": "PB6 - press", "test": "untested"}, {"fct": "button", "name": "PB6 - release", "test": "untested"}, {"fct": "button", "name": "PB7 - press", "test": "untested"}, {"fct": "button", "name": "PB7 - release", "test": "untested"}, {"fct": "button", "name": "PB8 - press", "test": "untested"}, {"fct": "button", "name": "PB8 - release", "test": "untested"}, {"fct": "button", "name": "PB9 - press", "test": "untested"}, {"fct": "button", "name": "PB9 - release", "test": "untested"}, {"fct": "button", "name": "PB10 - press", "test": "untested"}, {"fct": "button", "name": "PB10 - release", "test": "untested"}, {"fct": "button", "name": "PD1 - press", "test": "untested"}, {"fct": "button", "name": "PD1 - release", "test": "untested"}, {"fct": "button", "name": "PD2 - press", "test": "untested"}, {"fct": "button", "name": "PD2 - release", "test": "untested"}, {"fct": "button", "name": "PD3 - press", "test": "untested"}, {"fct": "button", "name": "PD3 - release", "test": "untested"}, {"fct": "joystick", "name": " - joystick", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "led", "name": "LED - led", "test": "untested"}, {"fct": "buzzer", "name": "BUZZER - buzzer", "test": "untested"}]', 'testuser', 'repair'),
(34, 'testPNFinal', 'testSerialFinal', 'finaltest', '2017-10-02 15:07:08', '[{"name": "PG1", "type": "button", "result": "TEST OK", "description": "Pref"}, {"name": "PG2", "type": "button", "result": "TEST OK", "description": "Sub"}, {"name": "PG3", "type": "button", "result": "TEST OK", "description": "N/L"}, {"name": "PG4", "type": "button", "result": "TEST OK", "description": "Store"}, {"name": "PG5", "type": "button", "result": "TEST OK", "description": "X ray timer"}, {"name": "PB1", "type": "button", "result": "TEST FAIL", "description": "FOV-"}, {"name": "PB2", "type": "button", "result": "TEST FAIL", "description": "FOV+"}, {"name": "PB3", "type": "button", "result": "TEST FAIL", "description": "Landscape-"}, {"name": "PB4", "type": "button", "result": "TEST FAIL", "description": "Landscape+"}, {"name": "PB5", "type": "button", "result": "TEST FAIL", "description": "Room light"}, {"name": "PB6", "type": "button", "result": "TEST OK", "description": "Spare Left"}, {"name": "PB7", "type": "button", "result": "TEST OK", "description": "Spare Middle"}, {"name": "PB8", "type": "button", "result": "TEST OK", "description": "Spare Right"}, {"name": "PB9", "type": "button", "result": "TEST OK", "description": "Operator-"}, {"name": "PB10", "type": "button", "result": "TEST OK", "description": "Operator+"}, {"name": "PD1", "type": "button", "result": "TEST OK", "description": "Stop"}, {"name": "PD2", "type": "button", "result": "TEST OK", "description": "S/E"}, {"name": "PD3", "type": "button", "result": "TEST OK", "description": "Test"}]', 'testuserfinal', 'repair'),
(35, 'testPNFinal', 'testSerialFinal', 'finaltest', '2017-10-02 15:16:59', '[{"name": "PG1", "type": "button", "result": "TEST OK", "description": "Pref"}, {"name": "PG2", "type": "button", "result": "TEST OK", "description": "Sub"}, {"name": "PG3", "type": "button", "result": "TEST OK", "description": "N/L"}, {"name": "PG4", "type": "button", "result": "TEST OK", "description": "Store"}, {"name": "PG5", "type": "button", "result": "TEST OK", "description": "X ray timer"}, {"name": "PB1", "type": "button", "result": "TEST FAIL", "description": "FOV-"}, {"name": "PB2", "type": "button", "result": "TEST FAIL", "description": "FOV+"}, {"name": "PB3", "type": "button", "result": "TEST FAIL", "description": "Landscape-"}, {"name": "PB4", "type": "button", "result": "TEST FAIL", "description": "Landscape+"}, {"name": "PB5", "type": "button", "result": "TEST FAIL", "description": "Room light"}, {"name": "PB6", "type": "button", "result": "TEST OK", "description": "Spare Left"}, {"name": "PB7", "type": "button", "result": "TEST OK", "description": "Spare Middle"}, {"name": "PB8", "type": "button", "result": "TEST OK", "description": "Spare Right"}, {"name": "PB9", "type": "button", "result": "TEST OK", "description": "Operator-"}, {"name": "PB10", "type": "button", "result": "TEST OK", "description": "Operator+"}, {"name": "PD1", "type": "button", "result": "TEST OK", "description": "Stop"}, {"name": "PD2", "type": "button", "result": "TEST OK", "description": "S/E"}, {"name": "PD3", "type": "button", "result": "TEST OK", "description": "Test"}]', 'testuserfinal', 'repair'),
(36, 'testPNFinal', 'testSerialFinal', 'finaltest', '2017-10-02 15:19:34', '[{"name": "PG1", "type": "button", "result": "TEST OK", "description": "Pref"}, {"name": "PG2", "type": "button", "result": "TEST OK", "description": "Sub"}, {"name": "PG3", "type": "button", "result": "TEST OK", "description": "N/L"}, {"name": "PG4", "type": "button", "result": "TEST OK", "description": "Store"}, {"name": "PG5", "type": "button", "result": "TEST OK", "description": "X ray timer"}, {"name": "PB1", "type": "button", "result": "TEST FAIL", "description": "FOV-"}, {"name": "PB2", "type": "button", "result": "TEST FAIL", "description": "FOV+"}, {"name": "PB3", "type": "button", "result": "TEST FAIL", "description": "Landscape-"}, {"name": "PB4", "type": "button", "result": "TEST FAIL", "description": "Landscape+"}, {"name": "PB5", "type": "button", "result": "TEST FAIL", "description": "Room light"}, {"name": "PB6", "type": "button", "result": "TEST OK", "description": "Spare Left"}, {"name": "PB7", "type": "button", "result": "TEST OK", "description": "Spare Middle"}, {"name": "PB8", "type": "button", "result": "TEST OK", "description": "Spare Right"}, {"name": "PB9", "type": "button", "result": "TEST OK", "description": "Operator-"}, {"name": "PB10", "type": "button", "result": "TEST OK", "description": "Operator+"}, {"name": "PD1", "type": "button", "result": "TEST OK", "description": "Stop"}, {"name": "PD2", "type": "button", "result": "TEST OK", "description": "S/E"}, {"name": "PD3", "type": "button", "result": "TEST OK", "description": "Test"}]', 'testuserfinal', 'repair');

-- --------------------------------------------------------

--
-- Structure de la table `log_sn`
--

CREATE TABLE `log_sn` (
  `id` int(11) NOT NULL,
  `part_number` varchar(255) NOT NULL,
  `serial_number` varchar(255) NOT NULL,
  `firmware` varchar(255) NOT NULL,
  `date` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Structure de la table `tsui`
--

CREATE TABLE `tsui` (
  `id` int(11) NOT NULL,
  `part_number` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `photo_link` varchar(255) NOT NULL,
  `family` int(50) NOT NULL,
  `linked_sequence` varchar(255) NOT NULL,
  `tst_name` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Contenu de la table `tsui`
--

INSERT INTO `tsui` (`id`, `part_number`, `name`, `photo_link`, `family`, `linked_sequence`, `tst_name`) VALUES
(1, 'test01', 'Agila', 'tsui1/tsui1.jpg', 1, '1', 'tst_01.pdf'),
(2, 'ELEGANCE', 'Elegance', 'tsui1/tsui1.jpg', 1, '1', 'tst_01.pdf'),
(3, 'a', 'Elegance', 'tsui1/tsui1.jpg', 1, '1', 'tst_01.pdf'),
(4, 'OMEGA', 'Omega', 'omega1/omega.jpg', 2, '2', 'tst_01.pdf'),
(5, 'SMARTBOX', 'SmartBox', 'smartbox1/smartbox.png', 3, '3', 'tst_01.pdf');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `dictionaries`
--
ALTER TABLE `dictionaries`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `global_log`
--
ALTER TABLE `global_log`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `log_sn`
--
ALTER TABLE `log_sn`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `tsui`
--
ALTER TABLE `tsui`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `dictionaries`
--
ALTER TABLE `dictionaries`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=66;
--
-- AUTO_INCREMENT pour la table `global_log`
--
ALTER TABLE `global_log`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;
--
-- AUTO_INCREMENT pour la table `log_sn`
--
ALTER TABLE `log_sn`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT pour la table `tsui`
--
ALTER TABLE `tsui`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
